FROM node:10.1.0

WORKDIR /home/node

COPY server/package.json server/package-lock.json server/

WORKDIR server

RUN npm install

COPY common/ ../common
RUN cd ../common/3dparty/vis && npm install && npm run build

COPY server/ ../server

RUN npm run build

#USER node

RUN mkdir ../data

VOLUME ["/home/app/config"]

EXPOSE 8080

CMD ["npm", "start"]
