# Build application
FROM node:alpine as builder
RUN apk add --no-cache git

WORKDIR /app/client/

COPY client/package.json client/package-lock.json /app/client/
COPY .git /app/
RUN cd /app/client && npm set progress=false && npm install


COPY common/ /app/common
RUN cd /app/common/3dparty/vis && npm install

COPY client/ /app/client
RUN cd /app/client && npm run build

# Serving file with nginx
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/client/dist /usr/share/nginx/html

COPY client/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
